"""adr_index.py の振る舞いを保証する。

保証すること（ADR-0003 決定 5）:
- 有効 ADR（proposed / accepted）を topic 別に索引化し要旨（summary）を併記、失効 ADR（superseded / deprecated）は別枠に出す
- frontmatter の必須項目（type / scope / updated / summary / status / topic）、語彙表に無い topic、片方向・自己参照・不在のリンク、
  失効なのに status が有効のままの ADR、連番重複、同 topic の既存 ADR を読んだ宣言（supersedes / amends / considered）の欠落を誤りとして報告する
- topic の偏り（10 本超）を警告し、それ以外では警告を出さない
- 語彙表（ADR ディレクトリの親の domain-terms.md、--terms で変更可）も INDEX.md も無いディレクトリだけを未移行として照合を省略する
  （ADR ディレクトリが無い・ディレクトリでない・読めない、--terms のパスが無い、語彙表が読めない、INDEX.md があるのに語彙表が無い、topic 表不在は error）
- --check で INDEX.md の陳腐化（CRLF 化を含む）を検出する
"""
import contextlib
import io
import os
import shutil
import sys
import tempfile
import textwrap
import unittest

sys.path.insert(0, os.path.dirname(__file__))
import adr_index  # noqa: E402

VOCAB = textwrap.dedent("""\
    # 用語と判断領域

    - `INDEX.md` は生成物（この箇条書きは語彙ではない）

    | topic | 意味 |
    |---|---|
    | `records` | 記録・開発運用の決め方 |
    | `platform` | 実行基盤と移行方式 |
    """)


def adr(num, title, status="accepted", topic="[records]", summary="要旨", **fields):
    fm = ["type: adr", "scope: all", f"status: {status}", "updated: 2026-09-04", f"topic: {topic}", f"summary: {summary}"]
    for k, v in fields.items():
        fm.append(f"{k}: {v}")
    return "---\n" + "\n".join(fm) + f"\n---\n\n# [ADR-{num}] {title}\n\n本文\n"


def section(index, heading):
    """見出し heading の直下から次の見出しまでの本文を返す。"""
    body = index.split(f"## {heading}", 1)[1]
    return body.split("\n## ", 1)[0]


def line_of(index, num):
    return [l for l in index.splitlines() if f"ADR-{num}" in l][0]


class AdrIndexCase(unittest.TestCase):
    def make_dir(self, vocab=VOCAB):
        """root/adr を ADR ディレクトリ、root/domain-terms.md を語彙表として作り、adr のパスを返す。"""
        root = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, root)
        d = os.path.join(root, "adr")
        os.mkdir(d)
        if vocab is not None:
            self.write(root, "domain-terms.md", vocab)
        return d

    def terms_path(self, d):
        return os.path.join(os.path.dirname(d), "domain-terms.md")

    def write(self, d, name, body):
        with open(os.path.join(d, name), "w", encoding="utf-8") as f:
            f.write(body)

    def read(self, d, name):
        with open(os.path.join(d, name), encoding="utf-8") as f:
            return f.read()

    def main(self, argv):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = adr_index.main(argv)
        return code, out.getvalue(), err.getvalue()


class IndexGeneration(AdrIndexCase):
    def test_active_adrs_are_listed_under_their_own_topic_in_vocab_order(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "基盤の話", topic="[platform]"))
        self.write(d, "0002-b.md", adr("0002", "記録の話", topic="[records]"))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertLess(result.index.index("## records"), result.index.index("## platform"))
        self.assertIn("[ADR-0002 記録の話](0002-b.md)", section(result.index, "records"))
        self.assertNotIn("ADR-0001", section(result.index, "records"))
        self.assertIn("[ADR-0001 基盤の話](0001-a.md)", section(result.index, "platform"))
        self.assertNotIn("ADR-0002", section(result.index, "platform"))

    def test_summary_is_shown_on_the_index_line(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", summary="索引だけで判断を絞れるようにする"))

        self.assertIn("索引だけで判断を絞れるようにする", line_of(adr_index.run(d).index, "0001"))

    def test_topic_heading_carries_the_vocab_description(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        self.assertIn("## records · 記録・開発運用の決め方", adr_index.run(d).index)

    def test_index_is_written_and_marked_as_generated_without_placeholders(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        adr_index.run(d, write=True)

        first = self.read(d, "INDEX.md").splitlines()[0]
        self.assertIn("generated by", first)
        self.assertNotIn("{aidd_root}", first)

    def test_index_names_the_terms_file_relative_to_adr_dir(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        self.assertIn("../domain-terms.md", adr_index.run(d).index)

    def test_proposed_is_active_and_deprecated_is_retired(self):
        d = self.make_dir()
        self.write(d, "0001-p.md", adr("0001", "提案中", status="proposed"))
        self.write(d, "0002-d.md", adr("0002", "廃止", status="deprecated"))

        index = adr_index.run(d).index

        self.assertIn("ADR-0001", section(index, "records"))
        self.assertNotIn("ADR-0002", section(index, "records"))
        self.assertIn("ADR-0002", section(index, "失効"))
        self.assertNotIn("ADR-0001", section(index, "失効"))

    def test_superseded_adr_is_listed_only_in_retired_section_with_successor(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[0002]"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0001]"))

        index = adr_index.run(d).index

        self.assertNotIn("ADR-0001", section(index, "records"))
        self.assertIn("0002", [l for l in section(index, "失効").splitlines() if "ADR-0001" in l][0])

    def test_supersedes_and_amends_are_shown_next_to_active_adr(self):
        d = self.make_dir()
        self.write(d, "0001-base.md", adr("0001", "土台", status="superseded", superseded_by="[0003]", amended_by="[0002]"))
        self.write(d, "0002-add.md", adr("0002", "補足", amends="[0001]"))
        self.write(d, "0003-new.md", adr("0003", "置換", supersedes="[0001]", considered="[0002]"))

        index = adr_index.run(d).index

        self.assertIn("amends 0001", line_of(index, "0002"))
        self.assertIn("supersedes 0001", line_of(index, "0003"))

    def test_multiple_topics_list_the_adr_under_each(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "両方", topic="[records, platform]"))
        self.write(d, "0002-b.md", adr("0002", "片方", topic="[platform]", considered="[0001]"))

        index = adr_index.run(d).index

        self.assertIn("ADR-0001", section(index, "records"))
        self.assertIn("ADR-0001", section(index, "platform"))
        self.assertNotIn("ADR-0002", section(index, "records"))

    def test_link_numbers_are_normalized(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[ADR-0002]"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[1]"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_title_is_taken_after_frontmatter_and_outside_code_fences(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", textwrap.dedent("""\
            ---
            type: adr
            scope: all
            status: accepted
            updated: 2026-09-04
            topic: [records]
            summary: s
            # frontmatter 内のコメント行は見出しではない
            ---

            ```
            # not the title
            ```

            # [ADR-0001] 本当の見出し
            """))

        self.assertIn("[ADR-0001 本当の見出し]", adr_index.run(d).index)


class FrontmatterFormats(AdrIndexCase):
    def test_block_list_and_inline_comment_are_read(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", textwrap.dedent("""\
            ---
            type: adr
            scope: all
            updated: 2026-09-04
            summary: s
            status: accepted  # 承認済み
            topic:
              - records
              - platform
            ---
            # [ADR-0001] x
            """))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertIn("ADR-0001", section(result.index, "platform"))

    def test_bom_and_leading_blank_lines_are_ignored(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", "﻿\n\n" + adr("0001", "x"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_missing_frontmatter_is_a_dedicated_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", "# [ADR-0001] x\n\n本文\n")

        errors = adr_index.run(d).errors

        self.assertEqual(len(errors), 1)
        self.assertIn("frontmatter が無い", errors[0])

    def test_scalar_topic_is_accepted(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="records"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_link_fields_may_be_omitted(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertIn("ADR-0001", result.index)

    def test_only_table_rows_of_vocab_count_as_topics(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[INDEX.md]"))

        self.assertTrue(any("INDEX.md" in e for e in adr_index.run(d).errors))

    def test_only_the_table_headed_topic_counts_as_vocab(self):
        d = self.make_dir(vocab=VOCAB + "\n| ファイル | 役割 |\n|---|---|\n| `INDEX.md` | 生成物 |\n")
        self.write(d, "0001-a.md", adr("0001", "x", topic="[INDEX.md]"))
        self.write(d, "0002-b.md", adr("0002", "y", topic="[platform]"))

        errors = adr_index.run(d).errors

        self.assertTrue(any("INDEX.md" in e for e in errors))
        self.assertFalse(any("platform" in e for e in errors))

    def test_scalar_followed_by_block_items_becomes_a_list(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", textwrap.dedent("""\
            ---
            type: adr
            scope: all
            updated: 2026-09-04
            summary: s
            status: accepted
            topic: records
              - platform
            ---
            # [ADR-0001] x
            """))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertIn("ADR-0001", section(result.index, "platform"))

    def test_vocab_without_a_topic_table_is_an_error(self):
        d = self.make_dir(vocab="# 語彙表\n\n| ファイル | 役割 |\n|---|---|\n| `INDEX.md` | 生成物 |\n")
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d)

        self.assertFalse(result.skipped)
        self.assertTrue(any("topic 表が無い" in e for e in result.errors))


class Validation(AdrIndexCase):
    def test_topic_not_in_vocab_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[nonsense]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "nonsense" in e for e in adr_index.run(d).errors))

    def test_missing_topic_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "topic" in e for e in adr_index.run(d).errors))

    def test_missing_required_fields_are_errors(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", "---\ntype:\nstatus: accepted\ntopic: [records]\n---\n# [ADR-0001] x\n")

        errors = adr_index.run(d).errors

        for key in ("type", "scope", "updated", "summary"):
            self.assertEqual(len([e for e in errors if e.startswith("ADR-0001:") and key in e]), 1, key)

    def test_wrong_type_and_malformed_updated_are_errors(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x").replace("type: adr", "type: design").replace("2026-09-04", "yesterday"))

        errors = adr_index.run(d).errors

        self.assertTrue(any("type 'design'" in e for e in errors))
        self.assertTrue(any("updated 'yesterday'" in e for e in errors))

    def test_self_reference_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0011-self.md", adr("0011", "自己参照", status="superseded", supersedes="[0011]", superseded_by="[0011]"))

        result = adr_index.run(d)

        self.assertTrue(any(e.startswith("ADR-0011:") and "自分自身" in e for e in result.errors))
        self.assertEqual(result.index, "")

    def test_one_way_supersedes_blames_the_adr_missing_the_back_link(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0001]"))

        errors = adr_index.run(d).errors

        self.assertTrue(any(e.startswith("ADR-0001:") and "superseded_by" in e for e in errors))
        self.assertFalse(any(e.startswith("ADR-0002:") for e in errors))

    def test_one_way_amended_by_blames_the_adr_missing_the_forward_link(self):
        d = self.make_dir()
        self.write(d, "0001-base.md", adr("0001", "土台", amended_by="[0002]"))
        self.write(d, "0002-add.md", adr("0002", "補足"))

        self.assertTrue(any(e.startswith("ADR-0002:") and "amends" in e for e in adr_index.run(d).errors))

    def test_link_to_unknown_adr_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0009]"))

        self.assertTrue(any(e.startswith("ADR-0002:") and "0009" in e for e in adr_index.run(d).errors))

    def test_back_link_to_unknown_adr_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[0009]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "0009" in e for e in adr_index.run(d).errors))

    def test_considered_pointing_to_unknown_adr_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", considered="[0009]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "considered" in e and "0009" in e for e in adr_index.run(d).errors))

    def test_superseded_by_without_superseded_status_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="accepted", superseded_by="[0002]"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0001]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "status" in e for e in adr_index.run(d).errors))

    def test_superseded_status_without_superseded_by_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "superseded_by" in e for e in adr_index.run(d).errors))

    def test_unknown_status_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", status="active"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "active" in e for e in adr_index.run(d).errors))

    def test_duplicate_number_is_reported_with_file_names_on_every_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "0001-b.md", adr("0001", "y", topic="[nonsense]"))

        errors = adr_index.run(d).errors

        self.assertTrue(any("重複" in e and "0001-b.md" in e for e in errors))
        self.assertTrue(any(e.startswith("ADR-0001 (0001-b.md):") and "nonsense" in e for e in errors))

    def test_index_is_not_written_when_errors_exist(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[nonsense]"))

        adr_index.run(d, write=True)

        self.assertFalse(os.path.exists(os.path.join(d, "INDEX.md")))

    def test_unmatched_markdown_file_is_warned_and_ignored_but_readme_is_silent(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "00042-old-style.md", adr("0042", "y", topic="[nonsense]"))
        self.write(d, "README.md", "# 説明\n")

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertTrue(any("00042-old-style.md" in w for w in result.warnings))
        self.assertFalse(any("README.md" in w for w in result.warnings))


class Coverage(AdrIndexCase):
    """同 topic の若い番号の有効 ADR は supersedes / amends / considered のどれかに現れなければならない。"""

    def test_unmentioned_same_topic_predecessor_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "先"))
        self.write(d, "0002-b.md", adr("0002", "後"))

        errors = adr_index.run(d).errors

        self.assertTrue(any(e.startswith("ADR-0002:") and "ADR-0001" in e and "considered" in e for e in errors))
        self.assertFalse(any(e.startswith("ADR-0001:") for e in errors))

    def test_considered_amends_or_supersedes_each_satisfy_coverage(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "a", amended_by="[0003]"))
        self.write(d, "0002-b.md", adr("0002", "b", considered="[0001]", superseded_by="[0004]", status="superseded"))
        self.write(d, "0003-c.md", adr("0003", "c", amends="[0001]"))
        self.write(d, "0004-d.md", adr("0004", "d", supersedes="[0002]", considered="[0001, 0003]"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_retired_and_other_topic_predecessors_need_no_mention(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "失効", status="deprecated"))
        self.write(d, "0002-b.md", adr("0002", "別領域", topic="[platform]"))
        self.write(d, "0003-c.md", adr("0003", "新"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_proposed_predecessor_also_requires_a_declaration(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "提案中", status="proposed"))
        self.write(d, "0002-b.md", adr("0002", "後"))

        self.assertTrue(any(e.startswith("ADR-0002:") and "ADR-0001" in e for e in adr_index.run(d).errors))

    def test_proposed_declarer_is_also_checked(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "先"))
        self.write(d, "0002-b.md", adr("0002", "提案中", status="proposed"))

        self.assertTrue(any(e.startswith("ADR-0002:") and "ADR-0001" in e for e in adr_index.run(d).errors))

    def test_comma_separated_considered_without_brackets_is_read_whole(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "a"))
        self.write(d, "0002-b.md", adr("0002", "b", considered="0001"))
        self.write(d, "0003-c.md", adr("0003", "c", considered="0001, 0002"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_higher_numbered_adrs_need_not_be_mentioned(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "先"))
        self.write(d, "0002-b.md", adr("0002", "後", considered="[0001]"))

        self.assertEqual(adr_index.run(d).errors, [])


class SkewWarnings(AdrIndexCase):
    def chain(self, d, numbers, topic="[records]", prefix="a"):
        previous = []
        for i in numbers:
            self.write(d, f"{i:04d}-{prefix}.md", adr(f"{i:04d}", f"x{i}", topic=topic, considered=f"[{', '.join(previous)}]"))
            previous.append(f"{i:04d}")

    def test_topic_with_more_than_ten_active_adrs_is_warned(self):
        d = self.make_dir()
        self.chain(d, range(1, 12))

        self.assertTrue(any("records" in w and "11" in w for w in adr_index.run(d).warnings))

    def test_exactly_ten_active_adrs_is_not_warned(self):
        d = self.make_dir()
        self.chain(d, range(1, 11))

        self.assertEqual(adr_index.run(d).warnings, [])

    def test_retired_adrs_do_not_count_toward_skew(self):
        d = self.make_dir()
        self.chain(d, range(1, 11))
        self.write(d, "0011-d.md", adr("0011", "廃止", status="deprecated"))

        self.assertEqual(adr_index.run(d).warnings, [])

    def test_skew_is_counted_per_topic_not_in_total(self):
        d = self.make_dir()
        self.chain(d, range(1, 7), topic="[records]", prefix="a")
        self.chain(d, range(7, 13), topic="[platform]", prefix="b")

        self.assertEqual(adr_index.run(d).warnings, [])

    def test_small_or_single_topics_are_not_warned(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[platform]"))
        self.write(d, "0002-b.md", adr("0002", "y"))
        self.write(d, "0003-c.md", adr("0003", "z", considered="[0002]"))

        self.assertEqual(adr_index.run(d).warnings, [])


class TermsLocation(AdrIndexCase):
    def test_missing_terms_and_index_skips_validation_with_a_warning(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x", status="active", topic="[]"))

        result = adr_index.run(d, write=True)

        self.assertTrue(result.skipped)
        self.assertEqual(result.errors, [])
        self.assertTrue(any("語彙表" in w for w in result.warnings))
        self.assertFalse(os.path.exists(os.path.join(d, "INDEX.md")))

    def test_index_without_terms_is_an_error_not_a_skip(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "INDEX.md", "stale\n")

        result = adr_index.run(d)

        self.assertFalse(result.skipped)
        self.assertTrue(any("INDEX.md があるのに" in e for e in result.errors))

    def test_explicit_terms_path_is_used(self):
        d = self.make_dir(vocab=None)
        other = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, other)
        self.write(other, "terms.md", VOCAB)
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d, terms=os.path.join(other, "terms.md"))

        self.assertEqual(result.errors, [])
        self.assertFalse(result.skipped)

    def test_explicit_terms_path_that_does_not_exist_is_an_error_not_a_skip(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d, terms=os.path.join(d, "nope.md"))

        self.assertFalse(result.skipped)
        self.assertTrue(any("--terms" in e for e in result.errors))

    def test_nonexistent_adr_dir_is_an_error_not_a_skip(self):
        result = adr_index.run(os.path.join(self.make_dir(), "nope"))

        self.assertFalse(result.skipped)
        self.assertTrue(any("存在しない" in e for e in result.errors))

    def test_file_given_as_adr_dir_is_an_error_saying_not_a_directory(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(os.path.join(d, "0001-a.md"))

        self.assertFalse(result.skipped)
        self.assertTrue(any("ディレクトリではない" in e for e in result.errors))

    @unittest.skipIf(getattr(os, "geteuid", lambda: -1)() == 0, "root は権限に関係なく読めるため検証できない")
    def test_unreadable_adr_dir_is_an_error_not_a_skip(self):
        d = self.make_dir()
        os.chmod(d, 0)
        self.addCleanup(os.chmod, d, 0o700)

        result = adr_index.run(d)

        self.assertFalse(result.skipped)
        self.assertTrue(any("読めない" in e for e in result.errors))

    @unittest.skipIf(getattr(os, "geteuid", lambda: -1)() == 0, "root は権限に関係なく読めるため検証できない")
    def test_unreadable_terms_file_is_an_error_not_a_skip(self):
        d = self.make_dir()
        os.chmod(self.terms_path(d), 0)
        self.addCleanup(os.chmod, self.terms_path(d), 0o600)
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d)

        self.assertFalse(result.skipped)
        self.assertTrue(any("読めない" in e for e in result.errors))

    def test_terms_that_is_a_directory_is_an_error_not_a_skip(self):
        d = self.make_dir(vocab=None)
        os.mkdir(self.terms_path(d))
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d)

        self.assertFalse(result.skipped)
        self.assertTrue(any("ファイルではない" in e for e in result.errors))

    def test_main_exits_zero_for_unmigrated_directory_even_with_check(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x", status="active"))

        code, out, err = self.main([d, "--check"])

        self.assertEqual(code, 0)
        self.assertIn("skipped", out)
        self.assertIn("語彙表", err)


class CheckMode(AdrIndexCase):
    def test_check_fails_when_index_is_stale(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "INDEX.md", "stale\n")

        code, _, err = self.main([d, "--check"])

        self.assertNotEqual(code, 0)
        self.assertIn("最新ではない", err)

    def test_check_fails_when_index_does_not_exist(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        self.assertNotEqual(self.main([d, "--check"])[0], 0)

    def test_check_fails_when_index_line_endings_were_converted_to_crlf(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.main([d])
        path = os.path.join(d, "INDEX.md")
        with open(path, encoding="utf-8", newline="") as f:
            content = f.read()
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.write(content.replace("\n", "\r\n"))

        self.assertNotEqual(self.main([d, "--check"])[0], 0)

    def test_check_passes_when_index_is_current_and_does_not_rewrite(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.main([d])
        written = os.path.getmtime(os.path.join(d, "INDEX.md"))

        code, out, _ = self.main([d, "--check"])

        self.assertEqual(code, 0)
        self.assertIn("ok", out)
        self.assertEqual(os.path.getmtime(os.path.join(d, "INDEX.md")), written)

    def test_main_returns_nonzero_and_reports_errors(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[nonsense]"))

        code, _, err = self.main([d])

        self.assertNotEqual(code, 0)
        self.assertIn("error: ADR-0001", err)


if __name__ == "__main__":
    unittest.main()
