"""adr_index.py の振る舞いを保証する。

保証すること（ADR-0003 決定 5）:
- 有効 ADR（proposed / accepted）を topic 別に索引化し、失効 ADR（superseded / deprecated）は別枠に出す
- 語彙表に無い topic、片方向リンク、失効なのに status が有効のままの ADR、連番重複を誤りとして報告する
- topic の偏り（10 本超）を警告し、それ以外では警告を出さない
- 語彙表も INDEX.md も無いディレクトリだけを未移行として照合を省略する（--vocab のパス不在や INDEX.md 残存は error）
- --check で INDEX.md の陳腐化を検出する
"""
import contextlib
import io
import os
import shutil
import sys
import tempfile
import textwrap
import unittest

sys.path.insert(0, os.path.dirname(__file__))
import adr_index  # noqa: E402

VOCAB = textwrap.dedent("""\
    # ADR topic 語彙表

    - `INDEX.md` は生成物（この箇条書きは語彙ではない）

    | topic | 意味 |
    |---|---|
    | `records` | 記録・開発運用の決め方 |
    | `platform` | 実行基盤と移行方式 |
    """)


def adr(num, title, status="accepted", topic="[records]", **links):
    fm = ["type: adr", "scope: all", f"status: {status}", "updated: 2026-09-04", f"topic: {topic}"]
    for k in ("supersedes", "superseded_by", "amends", "amended_by"):
        fm.append(f"{k}: {links.get(k, '[]')}")
    return "---\n" + "\n".join(fm) + f"\n---\n\n# [ADR-{num}] {title}\n\n本文\n"


def section(index, heading):
    """見出し heading の直下から次の見出しまでの本文を返す。"""
    body = index.split(f"## {heading}", 1)[1]
    return body.split("\n## ", 1)[0]


class AdrIndexCase(unittest.TestCase):
    def make_dir(self, vocab=VOCAB):
        d = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, d)
        if vocab is not None:
            self.write(d, "README.md", vocab)
        return d

    def write(self, d, name, body):
        with open(os.path.join(d, name), "w", encoding="utf-8") as f:
            f.write(body)

    def read(self, d, name):
        with open(os.path.join(d, name), encoding="utf-8") as f:
            return f.read()

    def main(self, argv):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = adr_index.main(argv)
        return code, out.getvalue(), err.getvalue()


class IndexGeneration(AdrIndexCase):
    def test_active_adrs_are_listed_under_their_own_topic_in_vocab_order(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "基盤の話", topic="[platform]"))
        self.write(d, "0002-b.md", adr("0002", "記録の話", topic="[records]"))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertLess(result.index.index("## records"), result.index.index("## platform"))
        self.assertIn("[ADR-0002 記録の話](0002-b.md)", section(result.index, "records"))
        self.assertNotIn("ADR-0001", section(result.index, "records"))
        self.assertIn("[ADR-0001 基盤の話](0001-a.md)", section(result.index, "platform"))
        self.assertNotIn("ADR-0002", section(result.index, "platform"))

    def test_topic_heading_carries_the_vocab_description(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        self.assertIn("## records · 記録・開発運用の決め方", adr_index.run(d).index)

    def test_index_is_written_and_marked_as_generated(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        adr_index.run(d, write=True)

        self.assertIn("generated by", self.read(d, "INDEX.md").splitlines()[0])

    def test_proposed_is_active_and_deprecated_is_retired(self):
        d = self.make_dir()
        self.write(d, "0001-p.md", adr("0001", "提案中", status="proposed"))
        self.write(d, "0002-d.md", adr("0002", "廃止", status="deprecated"))

        index = adr_index.run(d).index

        self.assertIn("ADR-0001", section(index, "records"))
        self.assertNotIn("ADR-0002", section(index, "records"))
        self.assertIn("ADR-0002", section(index, "失効"))
        self.assertNotIn("ADR-0001", section(index, "失効"))

    def test_superseded_adr_is_listed_only_in_retired_section_with_successor(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[0002]"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0001]"))

        index = adr_index.run(d).index

        self.assertNotIn("ADR-0001", section(index, "records"))
        retired_line = [l for l in section(index, "失効").splitlines() if "ADR-0001" in l][0]
        self.assertIn("0002", retired_line)

    def test_supersedes_and_amends_are_shown_next_to_active_adr(self):
        d = self.make_dir()
        self.write(d, "0001-base.md", adr("0001", "土台", status="superseded", superseded_by="[0003]", amended_by="[0002]"))
        self.write(d, "0002-add.md", adr("0002", "補足", amends="[0001]"))
        self.write(d, "0003-new.md", adr("0003", "置換", supersedes="[0001]"))

        index = adr_index.run(d).index

        self.assertIn("amends 0001", [l for l in index.splitlines() if "ADR-0002" in l][0])
        self.assertIn("supersedes 0001", [l for l in index.splitlines() if "ADR-0003" in l][0])

    def test_multiple_topics_list_the_adr_under_each(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "両方", topic="[records, platform]"))
        self.write(d, "0002-b.md", adr("0002", "片方", topic="[platform]"))

        index = adr_index.run(d).index

        self.assertIn("ADR-0001", section(index, "records"))
        self.assertIn("ADR-0001", section(index, "platform"))
        self.assertNotIn("ADR-0002", section(index, "records"))

    def test_link_numbers_are_normalized(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[ADR-0002]"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[1]"))

        self.assertEqual(adr_index.run(d).errors, [])


class FrontmatterFormats(AdrIndexCase):
    def test_block_list_and_inline_comment_are_read(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", textwrap.dedent("""\
            ---
            type: adr
            status: accepted  # 承認済み
            topic:
              - records
              - platform
            supersedes: []
            ---
            # [ADR-0001] x
            """))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertIn("ADR-0001", section(result.index, "platform"))

    def test_scalar_topic_is_accepted(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="records"))

        self.assertEqual(adr_index.run(d).errors, [])

    def test_only_table_rows_of_vocab_count_as_topics(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[INDEX.md]"))

        self.assertTrue(any("INDEX.md" in e for e in adr_index.run(d).errors))

    def test_only_the_table_headed_topic_counts_as_vocab(self):
        d = self.make_dir(vocab=VOCAB + textwrap.dedent("""

            | ファイル | 役割 |
            |---|---|
            | `INDEX.md` | 生成物 |
            """))
        self.write(d, "0001-a.md", adr("0001", "x", topic="[INDEX.md]"))
        self.write(d, "0002-b.md", adr("0002", "y", topic="[platform]"))

        errors = adr_index.run(d).errors

        self.assertTrue(any("INDEX.md" in e for e in errors))
        self.assertFalse(any("platform" in e for e in errors))

    def test_scalar_followed_by_block_items_becomes_a_list(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", textwrap.dedent("""\
            ---
            status: accepted
            topic: records
              - platform
            ---
            # [ADR-0001] x
            """))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertIn("ADR-0001", section(result.index, "platform"))


class Validation(AdrIndexCase):
    def test_topic_not_in_vocab_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[nonsense]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "nonsense" in e for e in adr_index.run(d).errors))

    def test_missing_topic_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "topic" in e for e in adr_index.run(d).errors))

    def test_one_way_supersedes_blames_the_adr_missing_the_back_link(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0001]"))

        errors = adr_index.run(d).errors

        self.assertTrue(any(e.startswith("ADR-0001:") and "superseded_by" in e for e in errors))
        self.assertFalse(any(e.startswith("ADR-0002:") for e in errors))

    def test_one_way_amended_by_blames_the_adr_missing_the_forward_link(self):
        d = self.make_dir()
        self.write(d, "0001-base.md", adr("0001", "土台", amended_by="[0002]"))
        self.write(d, "0002-add.md", adr("0002", "補足"))

        errors = adr_index.run(d).errors

        self.assertTrue(any(e.startswith("ADR-0002:") and "amends" in e for e in errors))

    def test_link_to_unknown_adr_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0009]"))

        self.assertTrue(any(e.startswith("ADR-0002:") and "0009" in e for e in adr_index.run(d).errors))

    def test_back_link_to_unknown_adr_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[0009]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "0009" in e for e in adr_index.run(d).errors))

    def test_superseded_by_without_superseded_status_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="accepted", superseded_by="[0002]"))
        self.write(d, "0002-new.md", adr("0002", "新", supersedes="[0001]"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "status" in e for e in adr_index.run(d).errors))

    def test_superseded_status_without_superseded_by_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-old.md", adr("0001", "旧", status="superseded"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "superseded_by" in e for e in adr_index.run(d).errors))

    def test_unknown_status_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", status="active"))

        self.assertTrue(any(e.startswith("ADR-0001:") and "active" in e for e in adr_index.run(d).errors))

    def test_duplicate_number_is_an_error(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "0001-b.md", adr("0001", "y"))

        self.assertTrue(any("重複" in e and "0001-b.md" in e for e in adr_index.run(d).errors))

    def test_index_is_not_written_when_errors_exist(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[nonsense]"))

        adr_index.run(d, write=True)

        self.assertFalse(os.path.exists(os.path.join(d, "INDEX.md")))

    def test_vocab_can_be_read_from_another_directory(self):
        d = self.make_dir(vocab=None)
        system = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d, vocab_path=os.path.join(system, "README.md"))

        self.assertEqual(result.errors, [])
        self.assertFalse(result.skipped)

    def test_unmatched_markdown_file_is_warned_and_ignored(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "00042-old-style.md", adr("0042", "y", topic="[nonsense]"))

        result = adr_index.run(d)

        self.assertEqual(result.errors, [])
        self.assertTrue(any("00042-old-style.md" in w for w in result.warnings))


class SkewWarnings(AdrIndexCase):
    def test_topic_with_more_than_ten_active_adrs_is_warned(self):
        d = self.make_dir()
        for i in range(1, 12):
            self.write(d, f"{i:04d}-a.md", adr(f"{i:04d}", f"x{i}"))

        self.assertTrue(any("records" in w and "11" in w for w in adr_index.run(d).warnings))

    def test_exactly_ten_active_adrs_is_not_warned(self):
        d = self.make_dir()
        for i in range(1, 11):
            self.write(d, f"{i:04d}-a.md", adr(f"{i:04d}", f"x{i}"))

        self.assertEqual(adr_index.run(d).warnings, [])

    def test_retired_adrs_do_not_count_toward_skew(self):
        d = self.make_dir()
        for i in range(1, 11):
            self.write(d, f"{i:04d}-a.md", adr(f"{i:04d}", f"x{i}"))
        self.write(d, "0011-d.md", adr("0011", "廃止", status="deprecated"))

        self.assertEqual(adr_index.run(d).warnings, [])

    def test_skew_is_counted_per_topic_not_in_total(self):
        d = self.make_dir()
        for i in range(1, 7):
            self.write(d, f"{i:04d}-a.md", adr(f"{i:04d}", f"x{i}", topic="[records]"))
        for i in range(7, 13):
            self.write(d, f"{i:04d}-b.md", adr(f"{i:04d}", f"y{i}", topic="[platform]"))

        self.assertEqual(adr_index.run(d).warnings, [])

    def test_small_or_single_topics_are_not_warned(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[platform]"))
        self.write(d, "0002-b.md", adr("0002", "y", topic="[records]"))
        self.write(d, "0003-c.md", adr("0003", "z", topic="[records]"))

        self.assertEqual(adr_index.run(d).warnings, [])


class UnmigratedDirectory(AdrIndexCase):
    def test_missing_vocab_skips_validation_with_a_warning(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x", status="active", topic="[]"))

        result = adr_index.run(d, write=True)

        self.assertTrue(result.skipped)
        self.assertEqual(result.errors, [])
        self.assertTrue(any("語彙表" in w for w in result.warnings))
        self.assertFalse(os.path.exists(os.path.join(d, "INDEX.md")))

    def test_explicit_vocab_path_that_does_not_exist_is_an_error_not_a_skip(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x"))

        result = adr_index.run(d, vocab_path=os.path.join(d, "nope", "README.md"))

        self.assertFalse(result.skipped)
        self.assertTrue(any("--vocab" in e for e in result.errors))

    def test_index_without_vocab_is_an_error_not_a_skip(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "INDEX.md", "stale\n")

        result = adr_index.run(d)

        self.assertFalse(result.skipped)
        self.assertTrue(any("INDEX.md" in e and "語彙表" in e for e in result.errors))

    def test_main_exits_zero_for_unmigrated_directory_even_with_check(self):
        d = self.make_dir(vocab=None)
        self.write(d, "0001-a.md", adr("0001", "x", status="active"))

        code, out, err = self.main([d, "--check"])

        self.assertEqual(code, 0)
        self.assertIn("skipped", out)
        self.assertIn("語彙表", err)


class CheckMode(AdrIndexCase):
    def test_check_fails_when_index_is_stale(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.write(d, "INDEX.md", "stale\n")

        code, _, err = self.main([d, "--check"])

        self.assertNotEqual(code, 0)
        self.assertIn("最新ではない", err)

    def test_check_fails_when_index_does_not_exist(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))

        self.assertNotEqual(self.main([d, "--check"])[0], 0)

    def test_check_passes_when_index_is_current_and_does_not_rewrite(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x"))
        self.main([d])
        written = os.path.getmtime(os.path.join(d, "INDEX.md"))

        code, out, _ = self.main([d, "--check"])

        self.assertEqual(code, 0)
        self.assertIn("ok", out)
        self.assertEqual(os.path.getmtime(os.path.join(d, "INDEX.md")), written)

    def test_main_returns_nonzero_and_reports_errors(self):
        d = self.make_dir()
        self.write(d, "0001-a.md", adr("0001", "x", topic="[nonsense]"))

        code, _, err = self.main([d])

        self.assertNotEqual(code, 0)
        self.assertIn("error: ADR-0001", err)


if __name__ == "__main__":
    unittest.main()
