"""adr_index.py の振る舞いを保証する。

保証すること（ADR-0003 決定 5）:
- 有効 ADR（proposed / accepted）を topic 別に索引化し、失効 ADR は別枠に出す
- 語彙表に無い topic、片方向リンク、失効なのに status が有効のままの ADR を誤りとして報告する
- topic の偏りを警告として報告する
- --check で INDEX.md の陳腐化を検出する
"""
import os
import sys
import tempfile
import textwrap
import unittest

sys.path.insert(0, os.path.dirname(__file__))
import adr_index  # noqa: E402

VOCAB = textwrap.dedent("""\
    # ADR topic 語彙表

    | topic | 意味 |
    |---|---|
    | `records` | 記録・開発運用の決め方 |
    | `platform` | 実行基盤と移行方式 |
    """)


def adr(num, title, status="accepted", topic="[records]", **links):
    fm = [f"type: adr", "scope: all", f"status: {status}", "updated: 2026-09-04", f"topic: {topic}"]
    for k in ("supersedes", "superseded_by", "amends", "amended_by"):
        fm.append(f"{k}: {links.get(k, '[]')}")
    return f"---\n" + "\n".join(fm) + f"\n---\n\n# [ADR-{num}] {title}\n\n本文\n"


class AdrDir:
    def __init__(self):
        self.dir = tempfile.mkdtemp()
        self.write("README.md", VOCAB)

    def write(self, name, body):
        with open(os.path.join(self.dir, name), "w") as f:
            f.write(body)
        return self

    def read(self, name):
        with open(os.path.join(self.dir, name)) as f:
            return f.read()


class IndexGeneration(unittest.TestCase):
    def test_active_adrs_are_grouped_by_topic_in_vocab_order(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "基盤の話", topic="[platform]"))
        d.write("0002-b.md", adr("0002", "記録の話", topic="[records]"))

        result = adr_index.run(d.dir)

        self.assertEqual(result.errors, [])
        self.assertLess(result.index.index("## records"), result.index.index("## platform"))
        self.assertIn("[ADR-0002 記録の話](0002-b.md)", result.index)
        self.assertIn("[ADR-0001 基盤の話](0001-a.md)", result.index)

    def test_index_is_written_and_marked_as_generated(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x"))

        adr_index.run(d.dir, write=True)

        self.assertIn("generated by", d.read("INDEX.md").splitlines()[0])

    def test_superseded_adr_is_listed_only_in_retired_section(self):
        d = AdrDir()
        d.write("0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[0002]"))
        d.write("0002-new.md", adr("0002", "新", supersedes="[0001]"))

        result = adr_index.run(d.dir)

        active, retired = result.index.split("## 失効")
        self.assertNotIn("ADR-0001", active)
        self.assertIn("ADR-0001", retired)
        self.assertIn("0002", retired.split("ADR-0001")[1].splitlines()[0])

    def test_relations_are_shown_next_to_active_adr(self):
        d = AdrDir()
        d.write("0001-base.md", adr("0001", "土台", amended_by="[0002]"))
        d.write("0002-add.md", adr("0002", "補足", amends="[0001]"))

        result = adr_index.run(d.dir)

        line = [l for l in result.index.splitlines() if "ADR-0002" in l][0]
        self.assertIn("amends 0001", line)

    def test_multiple_topics_list_the_adr_under_each(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "両方", topic="[records, platform]"))

        result = adr_index.run(d.dir)

        self.assertEqual(result.index.count("ADR-0001"), 2)

    def test_link_numbers_are_normalized(self):
        d = AdrDir()
        d.write("0001-old.md", adr("0001", "旧", status="superseded", superseded_by="[ADR-0002]"))
        d.write("0002-new.md", adr("0002", "新", supersedes="[1]"))

        result = adr_index.run(d.dir)

        self.assertEqual(result.errors, [])


class Validation(unittest.TestCase):
    def test_topic_not_in_vocab_is_an_error(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x", topic="[nonsense]"))

        result = adr_index.run(d.dir)

        self.assertTrue(any("nonsense" in e and "0001" in e for e in result.errors))

    def test_missing_topic_is_an_error(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x", topic="[]"))

        self.assertTrue(any("topic" in e for e in adr_index.run(d.dir).errors))

    def test_one_way_supersedes_link_is_an_error(self):
        d = AdrDir()
        d.write("0001-old.md", adr("0001", "旧"))
        d.write("0002-new.md", adr("0002", "新", supersedes="[0001]"))

        errors = adr_index.run(d.dir).errors

        self.assertTrue(any("0001" in e and "superseded_by" in e for e in errors))

    def test_one_way_amended_by_link_is_an_error(self):
        d = AdrDir()
        d.write("0001-base.md", adr("0001", "土台", amended_by="[0002]"))
        d.write("0002-add.md", adr("0002", "補足"))

        errors = adr_index.run(d.dir).errors

        self.assertTrue(any("0002" in e and "amends" in e for e in errors))

    def test_link_to_unknown_adr_is_an_error(self):
        d = AdrDir()
        d.write("0002-new.md", adr("0002", "新", supersedes="[0009]"))

        self.assertTrue(any("0009" in e for e in adr_index.run(d.dir).errors))

    def test_superseded_by_without_superseded_status_is_an_error(self):
        d = AdrDir()
        d.write("0001-old.md", adr("0001", "旧", status="accepted", superseded_by="[0002]"))
        d.write("0002-new.md", adr("0002", "新", supersedes="[0001]"))

        errors = adr_index.run(d.dir).errors

        self.assertTrue(any("0001" in e and "status" in e for e in errors))

    def test_unknown_status_is_an_error(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x", status="active"))

        self.assertTrue(any("active" in e for e in adr_index.run(d.dir).errors))

    def test_index_is_not_written_when_errors_exist(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x", topic="[nonsense]"))

        adr_index.run(d.dir, write=True)

        self.assertFalse(os.path.exists(os.path.join(d.dir, "INDEX.md")))

    def test_vocab_can_be_read_from_another_directory(self):
        d = AdrDir()
        os.remove(os.path.join(d.dir, "README.md"))
        vocab_dir = tempfile.mkdtemp()
        with open(os.path.join(vocab_dir, "README.md"), "w") as f:
            f.write(VOCAB)
        d.write("0001-a.md", adr("0001", "x"))

        result = adr_index.run(d.dir, vocab_path=os.path.join(vocab_dir, "README.md"))

        self.assertEqual(result.errors, [])


class SkewWarnings(unittest.TestCase):
    def test_topic_with_more_than_ten_adrs_is_warned(self):
        d = AdrDir()
        for i in range(1, 12):
            d.write(f"{i:04d}-a.md", adr(f"{i:04d}", f"x{i}"))

        warnings = adr_index.run(d.dir).warnings

        self.assertTrue(any("records" in w and "11" in w for w in warnings))

    def test_topic_with_single_adr_is_warned(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x", topic="[platform]"))

        warnings = adr_index.run(d.dir).warnings

        self.assertTrue(any("platform" in w for w in warnings))


class CheckMode(unittest.TestCase):
    def test_check_fails_when_index_is_stale(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x"))
        d.write("INDEX.md", "stale\n")

        self.assertNotEqual(adr_index.main([d.dir, "--check"]), 0)

    def test_check_passes_when_index_is_current(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x"))
        adr_index.main([d.dir])

        self.assertEqual(adr_index.main([d.dir, "--check"]), 0)

    def test_main_returns_nonzero_on_errors(self):
        d = AdrDir()
        d.write("0001-a.md", adr("0001", "x", topic="[nonsense]"))

        self.assertNotEqual(adr_index.main([d.dir]), 0)


if __name__ == "__main__":
    unittest.main()
